# -*- coding: utf-8 -*-
import io

APP = "/nfs/106072397/outputs/app.py"

INICIAL = [
    (1, "PROYECTO SOCIO INTEGRADOR: PRÁCTICA PROFESIONAL TRANSFORMADORA I", 9),
    (1, "EDUCACIÓN BOLIVARIANA Y SOCIEDAD", 2),
    (1, "USO SOCIAL DE LA LENGUA", 2),
    (1, "DESARROLLO Y CRECIMIENTO DEL NIÑO Y LA NIÑA EN EL CONTEXTO VENEZOLANO", 3),
    (1, "FORMACIÓN SOCIO CRÍTICA I", 3),
    (1, "GESTIÓN DE RIESGOS Y PROTECCIÓN CIVIL", 3),
    (2, "PROYECTO SOCIO INTEGRADOR: PRÁCTICA PROFESIONAL TRANSFORMADORA II", 8),
    (2, "PEDAGOGÍA TRANSFORMADORA", 3),
    (2, "CIMIENTOS DE LA EDUCACIÓN INICIAL", 3),
    (2, "LAS TICs EN LA EDUCACIÓN BOLIVARIANA", 3),
    (2, "LA ACTIVIDAD FÍSICA, EL JUEGO Y LA RECREACIÓN EN EDUCACIÓN INICIAL", 2),
    (2, "FORMACIÓN SOCIO CRÍTICA II", 3),
    (2, "LENGUAS INDÍGENAS (ELECTIVA)", 3),
    (3, "PROYECTO SOCIO INTEGRADOR: PRÁCTICA PROFESIONAL TRANSFORMADORA III", 9),
    (3, "MATEMÁTICA Y ESTADÍSTICA APLICADA A LO SOCIO EDUCATIVO", 3),
    (3, "EDUCACIÓN Y TERRITORIALIDAD", 3),
    (3, "CURRÍCULO EN EL SISTEMA EDUCATIVO VENEZOLANO", 3),
    (3, "TRADICIONES Y COSTUMBRES DEL PUEBLO VENEZOLANO", 2),
    (3, "AMBIENTE Y SALUD INTEGRAL", 3),
    (3, "FORMACIÓN SOCIO CRÍTICA III", 3),
    (4, "PROYECTO SOCIO INTEGRADOR: PRÁCTICA PROFESIONAL TRANSFORMADORA IV", 8),
    (4, "DESARROLLO SOCIO AFECTIVO Y LA INTELIGENCIA", 3),
    (4, "RESPONSABILIDAD SOCIAL FAMILIA ESCUELA Y COMUNIDAD", 3),
    (4, "EDUCACIÓN SEXUAL Y REPRODUCTIVA", 3),
    (4, "DESEMPEÑO PROFESIONAL DEL DOCENTE DE EDUCACIÓN INICIAL", 2),
    (4, "FORMACIÓN SOCIO CRÍTICA IV", 3),
    (4, "ALIMENTACIÓN SANA Y ALTERNATIVA EN EDUCACIÓN INICIAL (ELECTIVA)", 2),
    (5, "PROYECTO SOCIO INTEGRADOR: PRÁCTICA PROFESIONAL TRANSFORMADORA V", 9),
    (5, "PLANIFICACIÓN Y EVALUACIÓN EN EDUCACIÓN INICIAL", 3),
    (5, "DERECHOS HUMANOS DEL NIÑO Y LA NIÑA EN EL CONTEXTO EDUCATIVO VENEZOLANO", 3),
    (5, "PREVENCIÓN Y ATENCIÓN A LA SALUD INTEGRAL DEL NIÑO Y LA NIÑA", 3),
    (5, "EXPRESIÓN MUSICAL Y CORPORAL", 2),
    (5, "FORMACIÓN SOCIO CRÍTICA V", 3),
    (5, "SABERES ANCESTRALES DE LOS PUEBLOS INDÍGENAS", 2),
    (6, "PROYECTO SOCIO INTEGRADOR: PRÁCTICA PROFESIONAL TRANSFORMADORA VI", 8),
    (6, "EDUCACIÓN MATERNAL, LA GESTACIÓN Y EL PARTO HUMANIZADO", 3),
    (6, "DESARROLLO DE LA LENGUA ORAL Y LENGUA ESCRITA EN NIÑOS DE EDUCACIÓN INICIAL", 3),
    (6, "NECESIDADES EDUCATIVAS ESPECIALES Y ATENCIÓN A LA DIVERSIDAD", 3),
    (6, "EXPRESIÓN TEATRAL Y DANZAS TRADICIONALES DE VENEZUELA", 2),
    (6, "FORMACIÓN SOCIO CRÍTICA VI", 3),
    (6, "CREATIVIDAD E INNOVACIÓN EN EDUCACIÓN INICIAL (ELECTIVA)", 2),
    (7, "PROYECTO SOCIO INTEGRADOR: PRÁCTICA PROFESIONAL TRANSFORMADORA VII", 9),
    (7, "DESARROLLO DE LOS PROCESOS LÓGICO MATEMÁTICOS EN EL NIÑO DE EDUCACIÓN INICIAL", 3),
    (7, "EXPRESIÓN PLÁSTICA DEL NIÑO EN EDUCACIÓN INICIAL", 3),
    (7, "PROMOCIÓN DE LA LECTURA PARA NIÑOS Y NIÑAS DE EDUCACIÓN INICIAL", 2),
    (7, "FORMACIÓN SOCIO CRÍTICA VII", 3),
    (7, "TRANSFORMACIÓN DE MATERIALES Y RECURSOS PARA LA EDUCACIÓN INICIAL", 3),
    (8, "PROYECTO SOCIO INTEGRADOR: PRÁCTICA PROFESIONAL TRANSFORMADORA VIII", 8),
    (8, "PROCESOS ADMINISTRATIVOS EN LA EDUCACIÓN INICIAL EN VENEZUELA", 3),
    (8, "MEDIOS DE COMUNICACIÓN EN EDUCACIÓN INICIAL", 2),
    (8, "FORMACIÓN SOCIO CRÍTICA VIII", 3),
    (8, "CONTINUIDAD AFECTIVA Y ARTICULACIÓN PEDAGÓGICA EN EDUCACIÓN INICIAL (ELECTIVA)", 3),
    (8, "ACTIVIDADES ACADÉMICAS ACREDITABLES", 12),
]

ESPECIAL = [
    (5, "PROYECTO SOCIO INTEGRADOR V", 7),
    (5, "FORMACIÓN SOCIO CRÍTICA V", 4),
    (5, "EDUCACIÓN INTEGRAL PARA ESCOLARES CON DIFICULTADES DE APRENDIZAJES", 2),
    (5, "EDUCACIÓN INTEGRAL PARA LA PERSONA CON AUTISMO", 3),
    (5, "EVALUACIÓN PARA LA EDUCACIÓN ESPECIAL", 2),
    (5, "ENSEÑANZA Y ADAPTACIONES CURRICULARES PARA LA LECTURA, ESCRITURA Y MATEMÁTICA I", 3),
    (6, "PROYECTO SOCIO INTEGRADOR VI", 9),
    (6, "FORMACIÓN SOCIO CRÍTICA VI", 4),
    (6, "EDUCACIÓN INTEGRAL PARA LAS PERSONAS CON DISCAPACIDAD FÍSICO MOTORA", 3),
    (6, "EDUCACIÓN INTEGRAL PARA LA PERSONA CON ALTA POTENCIALIDAD", 2),
    (6, "ENSEÑANZA Y ADAPTACIONES CURRICULARES PARA LA LECTURA, ESCRITURA Y MATEMÁTICA II", 3),
    (7, "PROYECTO SOCIO INTEGRADOR VII", 9),
    (7, "FORMACIÓN SOCIO CRÍTICA VII", 4),
    (7, "EDUCACIÓN INTEGRAL PARA LAS PERSONAS CON DISCAPACIDAD SENSORIAL Y COMUNICACIONAL", 3),
    (7, "EDUCACIÓN INTEGRAL PARA LAS PERSONAS CON ENFERMEDADES ORGÁNICAS DISCAPACITANTES", 3),
    (7, "PREVENCIÓN Y ATENCIÓN INTEGRAL TEMPRANA", 2),
    (8, "PROYECTO SOCIO INTEGRADOR VIII", 9),
    (8, "FORMACIÓN SOCIO CRÍTICA VIII", 4),
    (8, "ORIENTACIÓN PARA LA INTEGRACIÓN LABORAL Y SOCIO COMUNITARIA", 3),
    (8, "ESTRATEGIAS PARA LA ORIENTACIÓN EDUCATIVA, FAMILIAR Y COMUNITARIA", 3),
    (8, "ADMINISTRACIÓN Y GESTIÓN DE LA EDUCACIÓN ESPECIAL", 3),
    (8, "ACTIVIDADES ACADÉMICAS ACREDITABLES II", 6),
]

def fmt(filas):
    lines = []
    for (po, mat, uc) in filas:
        m = mat.replace('"', '\\"')
        lines.append('        (%d, "SEMESTRE %d", "%s", %s),' % (po, po, m, uc))
    return "\n".join(lines)

block = '_MALLAS_OFICIALES = {\n    "LICENCIADO/A EN EDUCACIÓN, MENCIÓN EDUCACIÓN INICIAL": [\n%s\n    ],\n    "LICENCIADO/A EN EDUCACIÓN, MENCIÓN EDUCACIÓN ESPECIAL": [\n%s\n    ],\n}\n\n' % (fmt(INICIAL), fmt(ESPECIAL))

with io.open(APP, "r", encoding="utf-8") as f:
    src = f.read()

anchor = 'SELLO_PATHS = ["sello_secretaria.png", "sello_unem.png", "sello.png"]\n'
assert anchor in src, "anchor not found"
if "_MALLAS_OFICIALES = {" in src:
    print("ALREADY PRESENT, skipping")
else:
    src = src.replace(anchor, anchor + "\n" + block, 1)
    with io.open(APP, "w", encoding="utf-8") as f:
        f.write(src)
    print("inserted rows:", len(INICIAL), len(ESPECIAL))
